language: python
os: linux
dist: xenial
python:
  - '3.9'
install:
  - pip install -r requirements.txt
  - pip install -U pytest
script: python -m pytest -v
jobs:
  include:
    - stage: tests
      script: python -m pytest -v tests/test_dice.py
    - stage: deploy staging
      script: skip
      strategy: api
      deploy: &deploy
        provider: heroku
        api_key: $HEROKU_AUTH_TOKEN
        app: hw2-ci-me-dice
        on:
          repo: narvmtz/ci-me-dice-on-demand
          branch: main
    - stage: deploy to production
      script: skip
      strategy: api
      deploy:
        <<: *deploy
        app: hw2-ci-me-dice-prod
