language: python
os: linux
python:
  - '3.9'
install:
  - pip install -r requirements.txt
  - pip install -U pytest
script: python -m pytest -v
jobs:
  include:
    - stage: tests
      script: python -m pytest -v
    - stage: deploy staging
      script: skip
      deploy:
        provider: heroku
        api_key: $HEROKU_AUTH_TOKEN
        app: hw2-ci-me-dice
        on:
          repo: narvmtz/ci-me-dice-on-demand
          branch: main
    - stage: test deploy
      script: 'curl http://hw2-ci-me-dice.herokuapp.com'
