language: python
os: linux
dist: xenial
python:
  - '3.9'
install:
  - pip install -r requirements.txt
  - pip install -U pytest
script: python -m pytest -v
jobs:
  include:
    - stage: tests
      script: python -m pytest -v
    - stage: deploy staging
      script: skip
      deploy: &deploy
        provider: heroku
        strategy: api
        api_key: '$HEROKU_AUTH_TOKEN'
        app: hw2-ci-me-dice
        on:
          repo: narvmtz/ci-me-dice-on-demand
          branch: main
    - stage: deploy to production
      script: skip
      deploy:
        <<: *deploy
        app: hw2-ci-me-dice-prod
notifications:
  slack:
    rooms:
      - secure: uqmWX1oOLmQEfyFGRhE5EdBrWB8xnsiuaiZS25cTm41HM0R2HDNqJGQsfilZu7UMsoF/Whulbk8Ln4DF+dgSapCm0W+/2WJ3qHZAQcj3tlRzMTtIifusq9dbwUPDo0eULNaSn9DgHrjDe1MrcApq7RmoMzDL0jFzqyMI2VFuZLYrAfPQU6r8VfLMSItdAjjK4IS07MfKAN7qH0R4AuYbh6bEWjx7ktFEwrdykewP9fAboUKLgeUxglq6WP0YQ/PrLfaCOy7JyRNU0iuMmcyDc39dw5U45L8k8R606qU3LzrwKAY/27DoDqKAJ+a27cYVE5t86LD0syPA+02Tiu6y08KH7v1Q9aIyltbqDHwoPjsrIgsayXYMbMuvZQq1rzV7nduEgLaqIjc7jKmiweyQy8+UjU16Bq2eueUJHYQ3MxPKa+cPdW39aDo1LnsIyL0hcYiaeBqH0UjqDy//kMnOvG1G5jRKMh0BtFEu5js/NaHdOe+Zb5dlolRig5V92MBmjiyFopV/ejZv0a4ly2Xq3KSiLifZAsXGtfwU2tg8+eDlTJQmX8uCiWM7HJl1cQqRDAon3PCEeU2uqsNBJ63Ihj+tgt/aBgsPGpED3P23NZKeJNhzmPytq1C6Kev6tI3VhGoNvdVZ6gIqt3WxGMdaTwTJWPwY/bx+6jopENPff1o=
    on_success: change
    on_failure: always
